'use strict';

const questions = [
  {question: 'What is a baby seal called?',
    options: ['pup', 'guppy', 'cub', 'corki'],
    answer: 'pup',
    img: 'https://static.boredpanda.com/blog/wp-content/uploads/2016/11/cute-baby-seal-waves-photographer-alexey-trofimov-russia-fb__700-png.jpg',
    alt: 'An adorable baby seal!',
  },
  {question: 'Agent 007, featured in many movies dating back to 1962, is known as _______ Bond?',
    options: ['John', 'Benedict', 'James', 'Elizier'],
    answer: 'James',
    img:'https://banner2.kisspng.com/20180616/bvu/kisspng-james-bond-007-blood-stone-james-bond-film-series-007-quantum-of-solace-5b24e41b4e5767.5925889815291443473209.jpg',
    alt: 'The Double Oh 7 Symbol',
  },
  {question: 'What plant is traditionally the primary ingredient in wine?',
    options: ['agave', 'grape', 'peach', 'plum'],
    answer: 'grape',
    img:'https://static.vinepair.com/wp-content/uploads/2018/01/blackwine-internal.jpg',
    alt: 'A tempting glass of wine',
  },
  {question: 'Which civil rights activist was famous for refusing to give up her seat on a bus?',
    options: ['Dorothy Day', 'Rosa Parks', 'Jane Fonda', 'Emma Willard'],
    answer: 'Rosa Parks',
    img:'https://www.history.com/.image/ar_16:9%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cg_faces:center%2Cq_auto:good%2Cw_620/MTU3ODc3NjU3ODE4OTY1MzIx/montgomery-bus-boycott.jpg',
    alt: 'A famous historical bus',
  },
  {question: 'Which of these letters is not a vowel?',
    options: ['I', 'O', 'W', 'A'],
    answer: 'W',
    img:'https://www.talkingmats.com/wp-content/uploads/2013/09/talking-mats-who-we-are.jpg',
    alt: 'People talking with vowels',
  },
  {question: 'What is the head of the Roman Catholic Church called?',
    options: ['pope', 'master', 'cardinal', 'preacher'],
    answer: 'pope',
    img:'http://clipart-library.com/data_images/12939.png',
    alt: 'The head of the Roman Catholic Church',
  },
  {question: 'The poster for which film from the 1950s features three skipping characters, all dressed in bright yellow raincoats and swinging umbrellas?',
    options: ['Singin\' in the Rain', 'Sunset Boulevard', 'Vertigo', 'A Streetcar Named Desire'],
    answer: 'Singin\' in the Rain',
    img:'https://i.gyazo.com/28681323a01cee862314a0b9c4924487.png',
    alt: 'A famous poster of three people with raincoats and umbrellas',
  },
  {question: 'Newton is said to have been inspired by what to describe the theory of gravity?',
    options: ['ladder', 'hailstone', 'apple', 'rock'],
    answer: 'apple',
    img:'https://upload.wikimedia.org/wikipedia/commons/3/39/GodfreyKneller-IsaacNewton-1689.jpg',
    alt: 'Mr. Newton Himself',
  },
  {question: 'Which American town was famous for its witch trials?',
    options: ['Nashville, TN', 'Charleston, SC', 'Salem, MA', 'Portland, OR'],
    answer: 'Salem, MA',
    img:'https://assets.rebelcircus.com/blog/wp-content/uploads/2017/10/234234234-50.jpg',
    alt: 'A spooky witch',
  },
  {question: 'What chemical is added to U.S. water supplies in the hopes of improving dental health?',
    options: ['chlorine', 'flouride', 'bromine', 'hydrogen'],
    answer: 'fluoride',
    img:'https://www.well-beingsecrets.com/wp-content/uploads/how-to-whiten-teeth-800x416.jpg?x51046',
    alt: 'A perfect white smile',
  },
];